services:
  - type: web
    name: happypensacola-app
    env: python
    plan: free  # You can upgrade later as needed.
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn 'run:create_app'"
    envVars:
      - key: FLASK_ENV
        value: production
    healthCheckPath: /health
