services:
  - type: web
    name: happypensacola
    env: python
    plan: free
    region: oregon
    branch: main
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn 'run:create_app()'
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "0"
      - key: PORT
        value: "10000"
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: DATABASE_URL
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
