services:
  - type: web
    name: happypensacola
    env: python
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn 'run:create_app()'"
    envVars:
      - key: FLASK_ENV
        value: production
    healthCheckPath: /health
