"""Make date_of_birth nullable

Revision ID: 89737a90430f
Revises: 0bf3cb4a1261
Create Date: 2025-06-06 00:20:43.340567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89737a90430f'
down_revision = '0bf3cb4a1261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
